# 1. Build the Java app (Using Java 21 Maven image)
FROM maven:3.9-eclipse-temurin-21 AS build
COPY . .
RUN mvn clean package -DskipTests

# 2. Run the app (Using Java 21 Runtime)
FROM eclipse-temurin:21-jdk-alpine
COPY --from=build /target/*.jar app.jar

# Tell Spring Boot to use the port Render assigns
ENV SERVER_PORT=${PORT}
ENTRYPOINT ["java", "-Dserver.port=${PORT}", "-jar", "app.jar"]