# ----------------------------------------
# APPLICATION SETTINGS
# ----------------------------------------
server.port=8080

# ----------------------------------------
# CHESS ENGINE SELECTION
# ----------------------------------------
# Options: 'oop' or 'bitboard'
# This matches the @Profile("...") annotation in your Java classes
spring.profiles.active=bitboard